version: "3.7"
services:
  frontend:
    image: ghcr.io/namhyunki/kdt1-study-3-team4-front:latest
    container_name: docker-frontend-deploy-server
    ports:
      - "8080:8080"
    networks:
      - app

networks:
  app:
    driver: bridge